### ISSUE TITLE
Wrong hook used for toolbar manipulation

### ISSUE THREAD

**Issue by Rarst** [wecodemore/wcm_lang_switch#37]
The plugin currently uses `wp_before_admin_bar_render` hook for toolbar manipulation. This is a _render_ hook, that doesn't have access to `$wp_admin_bar` instance and is not meant to work with it.

The appropriate hook is `admin_bar_menu` which is explicitly documented for manipulating toolbar items and comes with `$wp_admin_bar` instance access.

**Comment by franz-josef-kaiser** [comment]
@Rarst did you give that hook a try? If not, would you give it a try when I open a PR and fix it on a separate branch?

**Comment by Rarst** [comment]
Not sure what you mean by "a try"?

Essentially the issue is that when correct hook is used then the same hook can (and should) be used to manipulate the toolbar nodes as necessary.

But since this plugin uses different hook it falls out of scope, so to say, and requires unique and entirely different code path to work with its nodes. A callback on the "right" hook would never see those nodes since they are registered after that  hook altogether.

**Comment by franz-josef-kaiser** [comment]
I am sorry, but I do not understand your last paragraph…

**Comment by Rarst** [comment]
You want to remove toolbar entries:

1. Everything registers nodes at `admin_bar_menu`
2. You hook into `admin_bar_menu` at 100 and remove all the nodes.
3. This plugin hooks into `wp_before_admin_bar_render` and adds its nodes, long after everything is supposed to be done.
